#!/bin/bash

SESSION_NAME="home"

# hack for macos
export PATH="/opt/homebrew/bin/:$PATH"

if [ -z "$TMUX" ]; then
  if [[ $(tput lines) > 30 ]]; then
    # Check if the session already exists
    tmux has-session -t $SESSION_NAME 2>/dev/null

    if [ $? -eq 0 ]; then
      # If the session exists, reattach to it
      tmux attach-session -t $SESSION_NAME
    else
      # If the session doesn't exist, start a new one
      tmux new-session -s $SESSION_NAME -d
      tmux attach-session -t $SESSION_NAME
    fi
  else
      # use standard fish shell for quick terminal in ghostty
      /usr/local/bin/fish
  fi
fi
