exec-once = hyprpaper
exec-once = proton-mail-bridge

exec-once = [workspace 1 silent] zen-browser
exec-once = [workspace 2 silent] ghostty
exec-once = [workspace 3 silent] slack
exec-once = [workspace 4 silent] thunderbird
exec-once = [workspace 5 silent] rancher-desktop

binds {
    allow_workspace_cycles = true
    workspace_back_and_forth = true
}
bind = SUPER, period, workspace, previous
bind = SUPER, SPACE, exec, ~/.config/hypr/scripts/launcher.sh                    # Open application launcher
