---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
words:
  - appropes
  - autocmd
  - automagically
  - autoread
  - autouse
  - bufnr
  - bufs
  - cfgs
  - chezmoi
  - cmac
  - cmacrae
  - codecompanion
  - codelldb
  - cookiecutter
  - dockerls
  - elif
  - endfor
  - entryfile
  - espflash
  - fastly
  - finalizers
  - fnameescape
  - fnamemodify
  - folke
  - ghidrah
  - ghpr
  - gmil
  - gmils
  - gopls
  - healthz
  - hearstapps
  - hikaru
  - hostnames
  - htmx
  - httproute
  - httproutes
  - httprouteversion
  - httprouteversions
  - hypr
  - igoringress
  - imdb
  - infri
  - ingressversion
  - ingressversions
  - jsonls
  - keybinds
  - keymap
  - kopf
  - kubefeature
  - kubeprod
  - loadtest
  - lsp
  - mcphub
  - noremap
  - nvim
  - opencode
  - primagean
  - rockspec
  - rustaceanvim
  - scaffolder
  - storystudio
  - stylesheet
  - taplo
  - venv
  - yamlls
  - zindex
